//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoloniexDemo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0WC09R2L-B2A7IP6C-F3GH0X5B-X06SWQPM")]
        public string PublicKey {
            get {
                return ((string)(this["PublicKey"]));
            }
            set {
                this["PublicKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46c95e7065a51198707d8ef1d0429749809b2f4ba57ceb0d60e8c28ac5ba4c3f40c7236f0948b1ac3" +
            "1f1220b027f8b148561e828688f16256ceabd14d64813f2")]
        public string PrivateKey {
            get {
                return ((string)(this["PrivateKey"]));
            }
            set {
                this["PrivateKey"] = value;
            }
        }
    }
}
